version: '3.8'
services:
  php-apache-env:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    ports:
      - '80:80'
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.0.0.2
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Password1!
      MYSQL_DATABASE: mailing
      MYSQL_USER: user
      MYSQL_PASSWORD: Password1!
    networks:
      vpcbr:
        ipv4_address: 10.0.0.3
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      vpcbr:
        ipv4_address: 10.0.0.4
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1